root: true
env:
  node: true
  es6: true
extends:
  - ../.eslintrc.yml
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
settings:
  'import/resolver':
    node:
      extensions:
        - js
        - jsx
        - ts
        - tsx
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
